---
title: "ExtraDE_Plots_Volcano"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("BiocManager")
#BiocManager::install("Seurat")
#BiocManager::install("ggplot2")
#BiocManager::install("sctransform")
#BiocManager::install("ggrastr")
#BiocManager::install("EnhancedVolcano")

library(Seurat)
library(ggplot2)
library(dplyr)
library(ape)
library(cowplot)
library(Matrix)
library(EnhancedVolcano)
library(knitr)
library(readr)
library(Hmisc)

#find out where you are
getwd()
```


```{r}
#Specify where your matrix files are
dir= "/Users/phinguyen/Dropbox (Personal)/Hen Lab/Data/SingleCell RNA-seq"
datafolder = "Data/Seurat"
filename = "1_Neuron_DG ONLY_25pert-Count-Feature-Cutoff_Downsampled_SCT_2022-8-9.RData"
organism = "Mouse"
#cellcyclefile = "https://raw.githubusercontent.com/lcdorman/scrnaseq/master/Spreadsheets/regev_lab_cell_cycle_genes.csv"

m = c("nCount_RNA","nFeature_RNA","percent.mito","percent.ribo")
Plotfolder = "Plots"

#if(organism == "Mouse"){library(org.Mm.eg.db)}
#if(organism == "Human"){library(org.Hs.eg.db)}
#if(organism == "Zebrafish"){library(org.Dr.eg.db)}
```

Load in your filtered dataset
```{r}
load(file.path(dir,datafolder,filename))
```

*Load in DE spreadsheet*
```{r}
dir= "/Users/phinguyen/Library/CloudStorage/Dropbox/Hen Lab/Collaborations/Adrienne Santiago/Spreadsheets/1_DGGCsECS vs Cort_Volcano.csv"

de = read.csv(file.path(dir),stringsAsFactors = F) #any spreadsheet with gene symbols or other identifiers

```


*Volcano Plot*
Vignette: https://www.bioconductor.org/packages/release/bioc/vignettes/EnhancedVolcano/inst/doc/EnhancedVolcano.html#introduction

Set your parameters
```{r}
#Minimum fold change (1.15x or 15% increase is equal to log2(1.15) = ~0.2)
minfc = 1.0
#Max adj. p value
alpha = 10e-8 
#Clusters selected
categories = levels(as.factor(de$cluster))
#Genes to highlight
ngenes = 10
```


Set up the spreadsheet for Volcano Plot (DE file with no cluster column and only looking at 1 cluster - *FindMarkers*) 
```{r}
colnames(de)[1] = "Genes"
head(de)
fc = de

colorkeysdown = fc$Gene[fc$avg_log2FC < -log2(minfc) & fc$p_val_adj < alpha]
colorkeysup = fc$Gene[fc$avg_log2FC > log2(minfc) & fc$p_val_adj < alpha]

#Either highlight specific genes or pick the top genes in colorkeysup/down
  top = fc[fc$p_val_adj<alpha,]
  top = top[order(top$avg_log2FC),"Genes"]
  highlight = c(head(top,ngenes),tail(top,ngenes))

  allcolors = rep("darkgrey",length(fc$Gene))
  names(allcolors) = fc$Gene
  
  allcolors[names(allcolors) %in% colorkeysup]= "brown2"
  allcolors[names(allcolors) %in% colorkeysdown] = "cornflowerblue"
  
  #allcolors[names(allcolors) %in% highlight]= "yellow"

  #names(allcolors)[allcolors == "yellow"] = "labelled"
  names(allcolors)[allcolors == "brown2"] = "up"
  names(allcolors)[allcolors == "darkgrey"] = "no sig change"
  names(allcolors)[allcolors == "cornflowerblue"] = "down"
  

  
```

```{r}
title = ""

genes_of_interest = Cs(Bdnf, Nrxn3, Necab3, Calb1, Nrg1, Nrg3, Rbfox3)

```

*Print Volcano plots*
```{r}
Volcano <- EnhancedVolcano(fc,
                lab = fc$Gene,
                x = 'avg_log2FC',
                y = 'p_val_adj',
                xlim = c(-2.5, 2.7),
                ylim = c(-3, 305),
                title = NULL,
                subtitle = "",
                legendPosition = 'none', # hide legend
                pCutoff = alpha,
                FCcutoff = log2(minfc),
                col=c('black', 'black', 'black', 'red3'),
                colCustom = allcolors,
                gridlines.major = F,
                gridlines.minor = F,
                colAlpha = 1,
                
                pointSize = 1.0, # dot size
                labSize = 5,  # label size
                axisLabSize = 14, # axes lab size
                drawConnectors = T,
                boxedLabels = T,
                lengthConnectors = unit(0.01, "npc"),
                selectLab = genes_of_interest,
                
                border = 'full',
                borderWidth = .5
                ) + theme(aspect.ratio=.75) 

Volcano 

```

*Save EPS file*
```{r}
dir = "path"

setEPS()
  postscript(file.path(dir,paste0("Volcano_",".eps")))
  print(EnhancedVolcano(fc,
                lab = fc$Gene,
                x = 'avg_log2FC',
                y = 'p_val_adj',
                xlim = c(-.6, .6),
                title = title,
                subtitle = "",
                legendPosition = 'none', # hide legend
                pCutoff = alpha,
                FCcutoff = log2(minfc),
                col=c('black', 'black', 'black', 'red3'),
                colCustom = allcolors,
                gridlines.major = F,
                gridlines.minor = F,
                colAlpha = 1,
                
                pointSize = 1.0, # dot size
                labSize = 3,  # label size
                axisLabSize = 14, # axes lab size
                drawConnectors = T,
                boxedLabels = T,
                lengthConnectors = unit(0.01, "npc"),
                selectLab = genes_of_interest,
                
                border = 'full',
                borderWidth = .5
                ) + theme(aspect.ratio=.75))
  dev.off()
```



***********